# Generated by Django 4.0.5 on 2022-06-30 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='userName',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
