# Generated by Django 3.1.14 on 2022-06-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.CharField(max_length=250)),
                ('pro_link', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='image/%')),
            ],
        ),
    ]
