# Generated by Django 4.0.5 on 2022-06-26 13:53

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to=projects.models.project_image_path),
        ),
    ]
