# Generated by Django 4.0.5 on 2022-06-24 14:03

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=services.models.category_image_path)),
                ('discription', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
