# Generated by Django 4.0.5 on 2022-06-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name_plural': 'Packages'},
        ),
    ]
