# Generated by Django 4.0.5 on 2022-06-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
                ('intro', models.TextField(max_length=800)),
                ('main', models.TextField(max_length=800)),
                ('img', models.ImageField(upload_to='image/blog')),
            ],
        ),
    ]
