# Generated by Django 4.0.5 on 2022-06-26 13:53

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(upload_to=blog.models.blog_image_path),
        ),
    ]
