# Generated by Django 4.0.5 on 2022-06-26 13:53

import aboutUs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='img',
            field=models.ImageField(upload_to=aboutUs.models.about_image_path),
        ),
    ]
