# Generated by Django 4.0.5 on 2022-06-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0002_alter_about_us_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name_plural': 'About_Us'},
        ),
    ]
