# Generated by Django 4.0.5 on 2022-06-29 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0003_alter_about_us_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='img',
            field=models.ImageField(upload_to='image/about'),
        ),
    ]
