# Generated by Django 4.0.5 on 2022-06-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='categoryName',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='name',
            new_name='packageName',
        ),
    ]
