# Generated by Django 4.0.5 on 2022-07-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_services_discription_services_list1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='List1',
            new_name='servicesList',
        ),
    ]
