# Generated by Django 4.0.5 on 2022-07-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_list1_services_serviceslist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='servicesList',
            new_name='servicesList1',
        ),
        migrations.AddField(
            model_name='services',
            name='servicesList2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='servicesList3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='servicesList4',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='servicesList5',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
