# Generated by Django 4.0.5 on 2022-07-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_serviceslist_services_serviceslist1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
